# docker-compose.yml
services:
  product-service:
    build: ./services/product
    ports:
      - "8001:8001"
    volumes:
      - ./data/sqlite:/app/db:ro
      - ./data/meta_Electronics.csv:/app/meta_Electronics.csv:ro


  rec-service:
    build: ./services/recommendation
    ports:
      - "8002:8002"
    volumes:
      - ./data/output_embeddings.json:/app/output_embeddings.json:ro
  user-service:
    build: ./services/user
    ports:
      - "8003:8003"

  review-service:
    build: ./services/review
    ports:
      - "8004:8004"
    volumes:
      - ./data/Electronics-5core.json:/app/reviews.jsonl:ro
      # mount thư mục db (host) → /app/db (container)
      - ./data/sqlite:/app/db


  ui-service:
    build: ./services/ui
    ports:
      - "7860:7860"
    volumes:
    - ./data/meta_Electronics.csv:/app/meta_Electronics.csv:ro
    depends_on:
      - product-service
      - rec-service
      - user-service
  react-ui-service:
    build:
      context: ./services/UI         # build context là thư mục chứa Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"                  # expose port 3000 ra host
    depends_on:
      - product-service
      - rec-service
      - user-service
      - review-service
