services:
  product-service:
    image: codemaivanngu/product-service:latest
    ports:
      - "8001:8001"
    volumes:
      - ./data/sqlite:/app/db:ro

  rec-service:
    image: codemaivanngu/rec-service:latest
    ports:
      - "8002:8002"

  user-service:
    image: codemaivanngu/user-service:latest
    ports:
      - "8003:8003"

  review-service:
    image: codemaivanngu/review-service:latest
    ports:
      - "8004:8004"
    volumes:
      - ./data/Electronics-5core.json:/app/reviews.jsonl:ro
      - ./data/sqlite:/app/db:ro

  ui-service:
    image: codemaivanngu/ui-service:latest
    ports:
      - "7860:7860"
    volumes:
      - ./data/meta_Electronics.csv:/app/meta_Electronics.csv:ro
    depends_on:
      - product-service
      - rec-service
      - user-service
  react-ui-service:
    image: codemaivanngu/react-ui-service:latest
    ports:
      - "3000:3000"                  # expose port 3000 ra host
    depends_on:
      - product-service
      - rec-service
      - user-service
      - review-service

# Notes:
# - Replace `your_dockerhub_username` with your actual Docker Hub account name.
# - `docker-compose.prod.yml` pulls images directly, so no build steps occur locally.
# - Keep host-volume mappings for read-only data as needed.